services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-mdop}"
    image: mlproject-data
    platform: linux/amd64
    container_name: mlproject-data-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-nhatminh}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-nhatminh}/.config/gcloud
      # authenticate to git
      - ~/.ssh:/home/${USER_NAME}/.ssh
    ports:
      #use jupyterlab with port 8888
      - 8888:8888
    ipc: host
    init: true